import argparse
import json
import sys
from pathlib import Path

import torch

try:
    from src.diffusers.models.transformers.transformer_imf import IMF_PRESET_CONFIGS, IMFTransformer2DModel
except ModuleNotFoundError:
    sys.path.append(str(Path(__file__).resolve().parents[1]))
    from src.diffusers.models.transformers.transformer_imf import IMF_PRESET_CONFIGS, IMFTransformer2DModel


def get_args():
    parser = argparse.ArgumentParser(description="Convert Diffusers iMF model back to legacy checkpoint format.")
    parser.add_argument("--model_path", type=str, required=True, help="Path to Diffusers model directory.")
    parser.add_argument("--output_path", type=str, required=True, help="Output legacy checkpoint path (.pth).")
    parser.add_argument(
        "--metadata_path",
        type=str,
        default=None,
        help="Optional conversion_metadata.json generated by convert_imf_to_diffusers.py.",
    )
    return parser.parse_args()


def _infer_model_type(model) -> str | None:
    model_type = getattr(model.config, "model_type", None)
    if model_type in IMF_PRESET_CONFIGS:
        return model_type
    for preset_name, preset in IMF_PRESET_CONFIGS.items():
        if (
            int(model.config.hidden_size) == int(preset["hidden_size"])
            and int(model.config.depth) == int(preset["depth"])
            and int(model.config.num_attention_heads) == int(preset["num_attention_heads"])
        ):
            return preset_name
    return None


def main():
    args = get_args()
    model_path = Path(args.model_path)
    transformer_path = model_path / "transformer" if (model_path / "transformer").exists() else model_path
    model = IMFTransformer2DModel.from_pretrained(str(transformer_path))

    metadata_path = Path(args.metadata_path) if args.metadata_path else model_path / "conversion_metadata.json"
    model_type = None
    if metadata_path.exists():
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        imf_args = metadata.get("imf_args", {})
        model_type = imf_args.get("model_type") or imf_args.get("model_str")
    if model_type is None:
        model_type = _infer_model_type(model)
    if model_type is None:
        raise ValueError("Could not infer iMF model_type. Pass --metadata_path from convert_imf_to_diffusers.py.")

    checkpoint = model.to_imf_checkpoint(prefix="net.")
    checkpoint["args"] = {"model_str": model_type, "model_type": model_type}

    output_path = Path(args.output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(checkpoint, str(output_path))
    print(f"Saved legacy checkpoint to: {output_path}")


if __name__ ==main__":
    main()
